#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Customize to your needs...
#

# Source Aliases
if [[ -s "${ZDOTDIR:-$HOME}/.bash_aliases" ]]; then
  source "${ZDOTDIR:-$HOME}/.bash_aliases"
fi

source $HOME/.homesick/repos/homeshick/homeshick.sh

homeshick --quiet refresh
